[Variables]
update=600
Background=1

toggle=[!ToggleMeter Comments][!ToggleMeter CommentsLogo][!ToggleMeter CommentsBackground][!ToggleMeter Title][!ToggleMeter TitleBackground][!ToggleMeter Image][!ToggleMeter MainBackground][!ToggleMeter 1I][!ToggleMeter 2I][!ToggleMeter 3I][!ToggleMeter 4I][!ToggleMeter twitter][!ToggleMeter pc17][!ToggleMeter steam][!ToggleMeter VersionText][!ToggleMeter VersionText2][!ToggleMeter VersionText3][!ToggleMeter Forum][!ToggleMeter HeaderBackground][!ToggleMeter Fpost][!ToggleMeter Fdate][!HideMeter BG-CATA][!HideMeter FeedT][!HideMeter CreationsT][!HideMeter MediaT][!HideMeter ModdingT][!HideMeter NewsT][!HideMeter TutT][!ToggleMeter BG-CATAO]
Ctoggle=[!ToggleMeter BG-CATA][!ToggleMeter FeedT][!ToggleMeter CreationsT][!ToggleMeter MediaT][!ToggleMeter ModdingT][!ToggleMeter NewsT][!ToggleMeter TutT]

logo=#SKINSPATH#\Lambda\Resources\Logo.png
commentlogo=#SKINSPATH#\Lambda\Resources\comment.png
Twitterlogo=#SKINSPATH#\Lambda\Resources\Twitterlogo.png
pc17logo=#SKINSPATH#\Lambda\Resources\pc17logo.png
Steamlogo=#SKINSPATH#\Lambda\Resources\steamlogo.png
OptionsBG=#SKINSPATH#\Lambda\Resources\optionsBG.png
Left=#SKINSPATH#\Lambda\Resources\Left.jpg
Right=#SKINSPATH#\Lambda\Resources\Right.jpg
Ficon=#SKINSPATH#\Lambda\Resources\Fileicon.png
CATA=#SKINSPATH#\Lambda\Resources\cata.png
CATAO=#SKINSPATH#\Lambda\Resources\catao.png
BG=#SKINSPATH#\Lambda\Resources\BG.png
BG2=#SKINSPATH#\Lambda\Resources\BG2.png
BG3=#SKINSPATH#\Lambda\Resources\BG3.png
BG4=#SKINSPATH#\Lambda\Resources\BG4.png
BG5=#SKINSPATH#\Lambda\Resources\BG5.png
BG6=#SKINSPATH#\Lambda\Resources\BG6.png

EP2=#SKINSPATH#\Lambda\Resources\EP2.png
Portal=#SKINSPATH#\Lambda\Resources\Portal.png
Tf2=#SKINSPATH#\Lambda\Resources\TF2.png
L4D=#SKINSPATH#\Lambda\Resources\L4D.png
FM=#SKINSPATH#\Lambda\Resources\FM.png

