[Variables]

// Drop Down menu Disc
disc=C

// Task Bar Width (in pixels)
Width=1000

// YouTube Subscription name for feed (Caps sensitive)
sub1=Google
sub2=TheOnion
sub3=pcgamer
sub4=nvidia

// Display the sub change links below the youtube widget, 0 = yes, 1 = no
disytimg=0

// Gmail account info (Caps sensitive)

GmailName=
GmailPass=

// Media player
// Edit Player= to have your player from this list of valid values available: http://rainmeter.net/cms/Plugins-NowPlaying_beta#playerlist

player=iTunes

