[Variables]
AccName=
updatesec=60
rssref=600
MenuC=192,192,192,255
RssC=255,255,255,255
XPc=255,100,0,255
LevelC=0,255,255,255
tooltip=0

URL=http://feeds.feedburner.com/steamgifts

minall=[!RainmeterHideMeter MenuBG][!RainmeterHideMeter MenuLinksBG][!RainmeterHideMeter account][!RainmeterHideMeter network][!RainmeterHideMeter giveaways][!RainmeterHideMeter GWmenubutton][!RainmeterHideMeter gwitemView][!RainmeterHideMeter gwitemfeat][!RainmeterHideMeter gwitemnew][!RainmeterHideMeter gwitemlatest][!RainmeterHideMeter ACCbutton][!RainmeterHideMeter ACsync][!RainmeterHideMeter ACemail][!RainmeterHideMeter ACreplies][!RainmeterHideMeter ACprofile][!RainmeterHideMeter nwsupport][!RainmeterHideMeter nwSgs][!RainmeterHideMeter nwst][!RainmeterHideMeter nwforum][!RainmeterHideMeter nwbutton]
menu=[!RainmeterShowMeter MenuLinksBG][!RainmeterShowMeter account][!RainmeterShowMeter network][!RainmeterShowMeter giveaways]
opengw=[!RainmeterShowMeter MenuBG][!RainmeterShowMeter GWmenubutton][!RainmeterShowMeter gwitemView][!RainmeterShowMeter gwitemfeat][!RainmeterShowMeter gwitemnew][!RainmeterShowMeter gwitemlatest]
openac=[!RainmeterShowMeter MenuBG][!RainmeterShowMeter ACprofile][!RainmeterShowMeter ACreplies][!RainmeterShowMeter ACemail][!RainmeterShowMeter ACsync][!RainmeterShowMeter ACCbutton]
opennt=[!RainmeterShowMeter MenuBG][!RainmeterShowMeter nwsupport][!RainmeterShowMeter nwSgs][!RainmeterShowMeter nwst][!RainmeterShowMeter nwforum][!RainmeterShowMeter nwbutton]
close=[!RainmeterHideMeter MenuBG][!RainmeterHideMeter GWmenubutton][!RainmeterHideMeter gwitemView][!RainmeterHideMeter gwitemfeat][!RainmeterHideMeter gwitemnew][!RainmeterHideMeter gwitemlatest][!RainmeterHideMeter ACprofile][!RainmeterHideMeter ACreplies][!RainmeterHideMeter ACemail][!RainmeterHideMeter ACsync][!RainmeterHideMeter ACCbutton][!RainmeterHideMeter nwsupport][!RainmeterHideMeter nwSgs][!RainmeterHideMeter nwst][!RainmeterHideMeter nwforum][!RainmeterHideMeter nwbutton]
close2=[!RainmeterHideMeter GWmenubutton][!RainmeterHideMeter gwitemView][!RainmeterHideMeter gwitemfeat][!RainmeterHideMeter gwitemnew][!RainmeterHideMeter gwitemlatest][!RainmeterHideMeter ACprofile][!RainmeterHideMeter ACreplies][!RainmeterHideMeter ACemail][!RainmeterHideMeter ACsync][!RainmeterHideMeter ACCbutton][!RainmeterHideMeter nwsupport][!RainmeterHideMeter nwSgs][!RainmeterHideMeter nwst][!RainmeterHideMeter nwforum][!RainmeterHideMeter nwbutton]




