[Variables]
update=600

toggle=[!ToggleMeter Comments][!ToggleMeter CommentsLogo][!ToggleMeter CommentsBackground][!ToggleMeter Title][!ToggleMeter TitleBackground][!ToggleMeter Image][!ToggleMeter MainBackground][!ToggleMeter 1I][!ToggleMeter 2I][!ToggleMeter 3I][!ToggleMeter 4I][!ToggleMeter pc17][!ToggleMeter steam][!ToggleMeter VersionText][!ToggleMeter VersionText2][!ToggleMeter VersionText3][!ToggleMeter Forum][!ToggleMeter HeaderBackground][!ToggleMeter Fpost][!ToggleMeter Fdate][!ToggleMeter BG-CATAO][!HideMeter FeedT][!HideMeter MagT][!HideMeter TechT][!HideMeter FreeT][!HideMeter BG-CATA]
Ctoggle=[!ToggleMeter BG-CATA][!ToggleMeter FeedT][!ToggleMeter MagT][!ToggleMeter TechT][!ToggleMeter FreeT]

logo=#SKINSPATH#\PCGamer\Resources\Logo.jpg
commentlogo=#SKINSPATH#\PCGamer\Resources\comment.png
RSS=#SKINSPATH#\PCGamer\Resources\RSS.png
Steamlogo=#SKINSPATH#\PCGamer\Resources\steamlogo.png
BG=#SKINSPATH#\PCGamer\Resources\BG.png
OptionsBG=#SKINSPATH#\PCGamer\Resources\optionsBG.png
Left=#SKINSPATH#\PCGamer\Resources\Left.jpg
Right=#SKINSPATH#\PCGamer\Resources\Right.jpg
SG=#SKINSPATH#\PCGamer\Resources\SG.png
Def=#SKINSPATH#\PCGamer\Resources\defualt.png
CATA=#SKINSPATH#\PCGamer\Resources\cata.png
CATAO=#SKINSPATH#\PCGamer\Resources\catao.png

