[Variables]
update=60

toggle=[!ToggleMeter Comments][!ToggleMeter CommentsLogo][!ToggleMeter CommentsBackground][!ToggleMeter Title][!ToggleMeter TitleBackground][!ToggleMeter Image][!ToggleMeter MainBackground][!ToggleMeter 1I][!ToggleMeter 2I][!ToggleMeter 3I][!ToggleMeter 4I][!ToggleMeter pc17][!ToggleMeter steam][!ToggleMeter VersionText][!ToggleMeter VersionText2][!ToggleMeter VersionText3][!ToggleMeter Forum][!ToggleMeter HeaderBackground][!ToggleMeter Fpost][!ToggleMeter Fdate]

logo=#SKINSPATH#\SteamGiftsV3\Resources\Logo.jpg
commentlogo=#SKINSPATH#\SteamGiftsV3\Resources\comment.png
RSS=#SKINSPATH#\SteamGiftsV3\Resources\RSS.png
Steamlogo=#SKINSPATH#\SteamGiftsV3\Resources\steamlogo.png
BG=#SKINSPATH#\SteamGiftsV3\Resources\BG.png
OptionsBG=#SKINSPATH#\SteamGiftsV3\Resources\optionsBG.png
Left=#SKINSPATH#\SteamGiftsV3\Resources\Left.jpg
Right=#SKINSPATH#\SteamGiftsV3\Resources\Right.jpg
SG=#SKINSPATH#\SteamGiftsV3\Resources\SG.png
Def=#SKINSPATH#\SteamGiftsV3\Resources\defualt.png

